openapi: "3.0.0"
info:
  version: 1.0.2
  title: CodeSum iam
  description: CodeSum iam service for User Authentication
  contact:
    name: Codesum
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

paths:
  /users/{id}:
    put:
      tags:
        - Users
      description: |
        Update User data
      operationId: updateUser
      parameters:
        - in: header
          required: true
          name: Access-token
          schema:
            type: string
        - name: id
          in: path
          description: User ID
          required: true
          schema:
            type: string
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: Update User
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '403':
          description: Invalid authorization for update user
        '404':
          description: User not found
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    get:
      tags:
        - Users
      description: |
        Get User
      operationId: getUserById
      parameters:
        - in: header
          required: true
          name: Access-token
          schema:
            type: string
        - name: id
          in: path
          description: User ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Find User
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '403':
          description: Invalid authorization for get user
        '404':
          description: User not found
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
        - Users
      description: |
        Delete User
      operationId: deleteUserById
      parameters:
        - in: header
          required: true
          name: Access-token
          schema:
            type: string
        - name: id
          in: path
          description: User ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User Deleted
        '403':
          description: Invalid authorization for delete user
        '404':
          description: User not found
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /users:
    post:
      tags:
        - Users
      description: |
        Create User
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: User Created
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /tokens:
    post:
      tags:
        - Token
      description: |
        Return token
      operationId: CreateToken
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: Token Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
        '403':
          description: Invalid authorization for create token
        '404':
          description: User not found
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /tokens/{id}:
    get:
      tags:
        - Token
      description: |
        Verify User's token
      operationId: getToken
      parameters:
        - in: header
          name: Access-token
          schema:
            type: string
        - in: header
          name: Refresh-token
          schema:
            type: string
        - name: id
          in: path
          description: User ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Token Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
        '403':
          description: Invalid authorization for get token
        '404':
          description: Token not found
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    User:
      type: object
      required:
        - email
        - password
      properties:
        id:
          type: string
          description: UUID for user
        nickName:
          type: string
          description: Nickname of user
        email:
          type: string
          description: Email for user
        password:
          type: string
          description: Password for user

    Token:
      type: object
      properties:
        access_token:
          type: string
          description: Access Token for user
        token_type:
          type: string
          description: Type of access_token.
        expires_at:
          type: integer
          description: Expire time
        refresh_at:
          type: integer
          description: Expire time
        refresh_token:
          type: string
          description: Refresh Token for access token
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string