// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.1 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	AccessToken string  `json:"access_token"`
	ExpiresIn   *int    `json:"expires_in,omitempty"`
	TokenType   *string `json:"token_type,omitempty"`
}

// UserLogin defines model for UserLogin.
type UserLogin struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	CreatedAt         *time.Time           `json:"created_at,omitempty"`
	Email             *openapi_types.Email `json:"email,omitempty"`
	Enabled           *bool                `json:"enabled,omitempty"`
	Id                *string              `json:"id,omitempty"`
	LastLoginAt       *time.Time           `json:"last_login_at,omitempty"`
	LoginFailCount    *int                 `json:"login_fail_count,omitempty"`
	Name              *string              `json:"name,omitempty"`
	Password          *string              `json:"password,omitempty"`
	PasswordChangedAt *time.Time           `json:"password_changed_at,omitempty"`
	RoleName          *string              `json:"role_name,omitempty"`
	UpdatedAt         *time.Time           `json:"updated_at,omitempty"`
	Username          *string              `json:"username,omitempty"`
}

// UserSignup defines model for UserSignup.
type UserSignup struct {
	Email    openapi_types.Email `json:"email"`
	Id       *string             `json:"id,omitempty"`
	Name     string              `json:"name"`
	Password string              `json:"password"`
	RoleName string              `json:"role_name"`
	Username string              `json:"username"`
}

// PostAuthLoginJSONBody defines parameters for PostAuthLogin.
type PostAuthLoginJSONBody UserLogin

// PostAuthSignupJSONBody defines parameters for PostAuthSignup.
type PostAuthSignupJSONBody UserSignup

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody PostAuthLoginJSONBody

// PostAuthSignupJSONRequestBody defines body for PostAuthSignup for application/json ContentType.
type PostAuthSignupJSONRequestBody PostAuthSignupJSONBody
